env:
  node: true
  es2022: true
extends:
  [
    eslint:recommended,
    plugin:@typescript-eslint/recommended,
    plugin:@typescript-eslint/recommended-requiring-type-checking,
    plugin:@typescript-eslint/strict
  ]
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ["./tsconfig.json"]
plugins: ["@typescript-eslint"]
rules:
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-unsafe-return": off
  "@typescript-eslint/restrict-template-expressions": off
  "@typescript-eslint/restrict-plus-operands": off
